### ISSUE TITLE
nftcollection.sol code

### ISSUE THREAD

**Issue by MuskaanMunu** [net2devcrypto/N2D-NFT-Marketplace#4]
Hi, How do we create the nftcollection.sol file, I have been following your tutorial and just now completed compiling my marketresale.sol file, I see we need the address of the nftcollection contract to progress.
Please help.

**Comment by AbuzarGhazanfarKhan** [comment]
[Nft Collection Smart Contract](https://www.youtube.com/watch?v=nZmEI0xKOqA)
deploy it...
copy the contract address and you are good to go
Oorrrr Bro create one yourself it will be a good practice

**Comment by MuskaanMunu** [comment]
Thank you!! :)
